name: CICD

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKERUSERNAME}} -p ${{secrets.DOCKERPASSWORD}}
      - name: Build docker image
        run: docker build -t thisismeshivam/application .
      - name: Publish image to docker hub
        run: docker push thisismeshivam/application:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker pull thisismeshivam/application:latest
      - name: Delete old container
        run: docker rm -f club_container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name club_container thisismeshivam/application
