name: CICD

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Start Docker service
        run: sudo service docker start

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERPASSWORD }}" | sudo docker login -u "${{ secrets.DOCKERUSERNAME }}" --password-stdin

      - name: Build Docker image
        run: sudo docker build -t thisismeshivam/application .

      - name: Publish image to Docker Hub
        run: sudo  docker push thisismeshivam/application:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: sudo docker pull thisismeshivam/application:latest

      - name: Delete old container (if exists)
        run: sudo docker stop club_container || true && sudo docker rm club_container || true

      - name: Run Docker container
        run: sudo docker run -d -p 8080:8080 --name club_container thisismeshivam/application
